name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # Frontend 빌드
      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install
        
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build:electron
          
      # Electron 빌드
      - name: Install Electron dependencies
        working-directory: ./electron
        run: npm install
        
      - name: Build and publish
        working-directory: ./electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash
        if: matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:mac
          else
            npm run build:linux
          fi

      - name: Build and publish (Windows)
        working-directory: ./electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'windows-latest'
        run: npm run build:win